---
- name: delete loopback and ospf process
  hosts: iou
  connection: local
  gather_facts: false
  
  tasks:
    - name: send configuration commands to IOS
      ansible.netcommon.telnet:
        port: 23
        user: admin
        password: "admin"
        login_prompt: 'Username: '
        prompts:
          - '[>#]'
        command:
          - configure terminal
          - crypto key generate rsa modulus 2048
