---
- name: Show interfaces
  hosts: R1
  connection: network_cli
  tasks:
    - name: use ios commands
      ios_command:
        commands:
          - show ip interface brief
      register: output
    - name: format output
      debug:
        msg: "{{ output.stdout_lines  }}"
      
