---
- name: Generate configuration file from template
  hosts: iou
  connection: network_cli
  gather_facts: no
  vars_files:
    - vars/router_vars.yml
  tasks:
    - name: Debug loop0
      debug:
        var: loop0_ip
    - name: Generate template
      template:
        src: templates/router_conf.j2
        dest: "conf_files/{{ inventory_hostname  }}.cfg"
